version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
    
hooks:
  BeforeInstall:
    - location: ./scripts/BeforeInstall.sh
      runas: root
  AfterInstall:
    - location: ./scripts/AfterInstall.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: ./scripts/ApplicationStop.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: ./scripts/ApplicationStart.sh
      timeout: 3600
      runas: root